### ISSUE TITLE
I have encountered some errors. Can you please tell me your Python version

### ISSUE THREAD

**Issue by njx2003** [yakhyo/unet-pytorch#9]

**Comment by yakhyo** [comment]
@njx2003 , 

Python version: 3.10

**Comment by njx2003** [comment]
According to the download link you provided, why are all the images in the train_mask folder black instead of the ones provided on the official website
![L`1ZLAOQLJH VHQ9$_JH288](https://github.com/yakhyo/unet-pytorch/assets/131862479/a365de49-42cb-4513-aa54-89dd38c433db)
![( LHLZ%FREH@F_ZDW583$ZW](https://github.com/yakhyo/unet-pytorch/assets/131862479/e5a9148b-b58c-44ee-b924-ff5ef1cbecca)

**Comment by yakhyo** [comment]
@njx2003 , 

Yes, because they are class ID masks. 
In original dataset, those masks are colored masks (in here white and black) however those needs to be converted to class ID masks for training.
Therefore, I used ready-to-go masks that were already prepared as class ID masks.

You can check the picture below and understand what is class ID mask. 
![image](https://github.com/yakhyo/unet-pytorch/assets/28424328/223bddfb-ca71-497a-b799-a4da5e63217a)

**Comment by njx2003** [comment]
@yakhyo 
Thank you for your patient answer！
